version: '3'

services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: M!qn918mf=3g
      MYSQL_DATABASE: taskflow
    volumes:
      - './data/etc/mysql/:/etc/mysql/'
      - './data/var/lib/mysql/:/var/lib/mysql/'
      
  app:
    image: docker.io/bitnami/laravel:9
    restart: unless-stopped
    ports:
      - '8000:8000'
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USERNAME: root
      DB_DATABASE: taskflow
      DB_PASSWORD: M!qn918mf=3g
    volumes:
      - './data/app/:/app'
    depends_on:
      - mariadb
      
  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_POST: 3306
      PMA_PMADB: pmadb
    depends_on:
      - mariadb
  